/**
 * Canonical Phase-0 IR fixtures (implemenation_plam/TASKS.md Phase 0).
 * Hand-built IR standing in for Blocks→IR lowering (Phase 1); each carries
 * the expected Arduino C the printer must emit, deterministically.
 */
import type { ProgramIR } from '../ir/types';
import {
  assign,
  bin,
  bool,
  delayMs,
  digitalWrite,
  forRange,
  global,
  iff,
  millis,
  not,
  pinModeStmt,
  program,
  readDigital,
  serialPrintln,
  servoAttach,
  servoWrite,
  str,
  variable,
} from './builders';

// --- Blink: LED on D13, 500ms on / 500ms off ---
export const blinkProgram: ProgramIR = program({
  loop: [digitalWrite('D13', true), delayMs(500), digitalWrite('D13', false), delayMs(500)],
});

export const blinkExpectedC = `// Generated by Pinboard
// Board: Arduino Uno

void setup() {
  pinMode(13, OUTPUT);
}

void loop() {
  digitalWrite(13, HIGH);
  delay(500);
  digitalWrite(13, LOW);
  delay(500);
}
`;

// --- Blink Without Delay: millis()-based toggle (the clock litmus test) ---
export const blinkWithoutDelayProgram: ProgramIR = program({
  globals: [global('ledState', 'boolean', bool(false)), global('lastToggleMs', 'number', { kind: 'num', value: 0 })],
  loop: [
    iff(bin('>=', bin('-', millis(), variable('lastToggleMs')), 500), [
      assign('ledState', not(variable('ledState'))),
      digitalWrite('D13', variable('ledState')),
      assign('lastToggleMs', millis()),
    ]),
  ],
});

export const blinkWithoutDelayExpectedC = `// Generated by Pinboard
// Board: Arduino Uno

bool ledState = false;
long lastToggleMs = 0;

void setup() {
  pinMode(13, OUTPUT);
}

void loop() {
  if (millis() - lastToggleMs >= 500) {
    ledState = !ledState;
    digitalWrite(13, ledState);
    lastToggleMs = millis();
  }
}
`;

// --- Button Controls LED: internal pull-up button on D2, LED on D13 ---
// The pinMode(D2, INPUT_PULLUP) node is what Blocks→IR lowering emits from
// the button's pullMode config (codegen.md §6); pressed reads LOW.
export const buttonControlsLedProgram: ProgramIR = program({
  setup: [pinModeStmt('D2', 'INPUT_PULLUP')],
  loop: [
    iff(
      bin('==', readDigital('D2'), bool(false)),
      [digitalWrite('D13', true), serialPrintln(str('Button pressed'))],
      [digitalWrite('D13', false)],
    ),
    delayMs(20),
  ],
});

export const buttonControlsLedExpectedC = `// Generated by Pinboard
// Board: Arduino Uno

void setup() {
  pinMode(2, INPUT_PULLUP);
  pinMode(13, OUTPUT);
  Serial.begin(9600);
}

void loop() {
  if (digitalRead(2) == LOW) {
    digitalWrite(13, HIGH);
    Serial.println("Button pressed");
  } else {
    digitalWrite(13, LOW);
  }
  delay(20);
}
`;

// --- Servo Sweep: forRange drives a servo on D9 (runtime test 14) ---
export const servoSweepProgram: ProgramIR = program({
  setup: [servoAttach('arm', 'D9')],
  loop: [forRange('angle', 0, 180, 45, [servoWrite('arm', variable('angle')), delayMs(15)])],
});

export const servoSweepExpectedC = `// Generated by Pinboard
// Board: Arduino Uno

#include <Servo.h>

Servo arm;

void setup() {
  arm.attach(9);
}

void loop() {
  for (long angle = 0; angle <= 180; angle += 45) {
    arm.write(angle);
    delay(15);
  }
}
`;
